project:
  type: website
  output-dir: _site
  render: 
    - "*.qmd"
    - "*.md"  
  resources: 
    - "/images/"
    - "/venue/CSU-Spur-Hydro-map.pdf"

website:
  title: "Trees in the West"
  favicon: images/favicon.png
  search: 
    location: navbar
    type: textbox
  site-url: https://www.treesinthewest.com
  repo-url: https://github.com/danielburcham/treesinthewest-quarto-site
  google-analytics: "G-4K0CFEWX4K"
  navbar:
    logo: images/conferenceLogo.png
    logo-alt: "Trees in the West conference logo"
    collapse: true
    title: false
    left:
      - href: schedule\index.qmd
        text: Schedule
      - href: speakers\index.qmd
        text: Speakers
      - href: venue\index.qmd
        text: Venue
    right:
      - href: https://www.eventbrite.com/e/trees-in-the-west-tickets-1231591024909
        text: Register
  page-footer: 
    left: ""
    center: |
      **Organizing Partners**  
        
      [![](/images/csuLogo.png){height=70px}](https://www.colostate.edu){target=blank} [![](/images/csuSpurLogo.png){height=70px}](https://www.csuspur.org){target=blank} [![](/images/csfsLogo.png){height=70px}](https://csfs.colostate.edu){target=blank}
    right: ""

format:
  html:
    embed-resources: true
    theme: 
      - cosmo
      - styles.scss
    mainfont: Poppins
    toc: false
css: styles.css
