---
title: "Venue"
format: html
---

The event will take place in the Confluence Theater located in the Hydro building at CSU Spur. Located on the ground floor, the Theater can accommodate over 250 people with access to outdoor areas, including the Research Grove. During the event, registrants can enjoy beverages, snacks, and a catered lunch. 

[Download a map of conference locations](CSU-Spur-Hydro-map.pdf){target=blank}

### Directions
::: {.column-body-outset style="padding-top: 3%; padding-bottom: 3%;"}
```{=html}
<html>
<head>
<meta charset="utf-8">
<link href='https://api.mapbox.com/mapbox-gl-js/v3.6.0/mapbox-gl.css' rel='stylesheet' />
<script src='https://api.mapbox.com/mapbox-gl-js/v3.6.0/mapbox-gl.js'></script>
</head>
<body>
<style>
    .mapboxgl-popup {
        max-width: 400 px;
        font:
            12px/20px 'Poppins',
            Arial,
            Helvetica,
            sans-serif;
    }
</style>

<script src="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-directions/v4.3.1/mapbox-gl-directions.js"></script>
<link rel="stylesheet" href="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-directions/v4.3.1/mapbox-gl-directions.css" type="text/css">

<div id='map' style='width: 100%; height: 500px;'></div>
<script>
mapboxgl.accessToken = 'pk.eyJ1IjoiZGFuaWVsYnVyY2hhbSIsImEiOiJjbTY3Y2V1eTgwMXE4Mm1vOTBqYXFuNW5pIn0.7yGIge9qLSJZqNmlfNAIdA';

const map = new mapboxgl.Map({
	container: 'map', // container ID
	style: 'mapbox://styles/mapbox/streets-v12', // style URL
	center: [-104.974, 39.784], // starting position [lng, lat]
	zoom: 15, // starting zoom
});

var directions = new MapboxDirections({
        accessToken: mapboxgl.accessToken
        
    });

map.addControl(directions,'top-left');

map.on('load',  function() {
    directions.setDestination("4777 North National Western Drive, Denver, CO 80216");
})

</script>
</body>
</html>
```
:::

### Parking
Free visitor parking is available on the north side of the Vida building at CSU Spur. 

### Alternative Transportation
The RTD N Line station at E 48th Ave and Brighton Blvd at the National Western Center is the nearest light rail station. You can walk from the train station to CSU Spur along Bettie Cram Drive or E 46th Ave.

For cyclists, the South Platte River bike trail connects directly to CSU Spur, and the campus has bike racks in several locations. 
